import type { ContentBundle } from '../core/types';

export const defaultContent: ContentBundle = {
  resources: [
    {
      id: 'resource.knowledge',
      name: '知识',
      description: '点击知识地图的空白处即可获得。',
      icon: '/assets/knowledge.svg',
      tags: ['core'],
      initialAmount: 0,
      visible: true,
    },
    {
      id: 'resource.math',
      name: '数学理解',
      description: '由数学类生产者持续积累。',
      icon: '/assets/math.svg',
      tags: ['mathematics'],
      initialAmount: 0,
      visible: true,
    },
    {
      id: 'resource.music',
      name: '音乐经验',
      description: '示例：未来任何领域都能用相同框架接入。',
      icon: '/assets/music.svg',
      tags: ['music'],
      initialAmount: 0,
      visible: true,
    },
  ],
  producers: [
    {
      id: 'producer.learning',
      name: '学习',
      description: '第一台生产者。升级它，让主动点击逐渐变成自动积累。',
      image: '/assets/study.svg',
      category: '起点',
      tags: ['core', 'learning'],
      baseCost: [{ resourceId: 'resource.knowledge', amount: 8 }],
      costScaling: 1.17,
      production: [{ resourceId: 'resource.knowledge', amountPerSecond: 0.45 }],
      unlockCondition: { type: 'always' },
      graph: { x: 780, y: 620 },
      enabled: true,
    },
    {
      id: 'producer.math.foundation',
      name: '数学基础',
      description: '一个新的生产者分支。它与前面的技能相连，但仍使用完全相同的 Producer 核心。',
      image: '/assets/math.svg',
      category: '数学',
      tags: ['mathematics', 'academic'],
      baseCost: [{ resourceId: 'resource.knowledge', amount: 140 }],
      costScaling: 1.19,
      production: [{ resourceId: 'resource.math', amountPerSecond: 0.85 }],
      unlockCondition: { type: 'upgrade_tag_count_at_least', tag: 'learning', count: 3 },
      graph: { x: 1220, y: 620, parentId: 'upgrade.learning.focus' },
      enabled: true,
    },
    {
      id: 'producer.math.calculus',
      name: '微积分',
      description: '第二层数学生产者。技能可继续挂在它周围。',
      image: '/assets/calculus.svg',
      category: '数学',
      tags: ['mathematics', 'science', 'academic'],
      baseCost: [{ resourceId: 'resource.math', amount: 90 }],
      costScaling: 1.2,
      production: [{ resourceId: 'resource.math', amountPerSecond: 2.4 }],
      unlockCondition: { type: 'upgrade_level_at_least', upgradeId: 'upgrade.math.algebra', level: 1 },
      graph: { x: 1660, y: 620, parentId: 'upgrade.math.algebra' },
      enabled: true,
    },
  ],
  upgrades: [
    {
      id: 'upgrade.learning.observe',
      name: '观察',
      description: '学习生产效率 ×1.25。',
      image: '/assets/notes.svg',
      category: '学习技能',
      tags: ['learning'],
      cost: [{ resourceId: 'resource.knowledge', amount: 18 }],
      unlockCondition: { type: 'producer_level_at_least', producerId: 'producer.learning', level: 2 },
      effects: [{ type: 'producer_multiplier', target: { kind: 'producer', id: 'producer.learning' }, value: 1.25 }],
      graph: { x: 680, y: 390, parentId: 'producer.learning' },
    },
    {
      id: 'upgrade.learning.memory',
      name: '记忆方法',
      description: '学习生产效率 ×1.35。',
      image: '/assets/limit.svg',
      category: '学习技能',
      tags: ['learning'],
      cost: [{ resourceId: 'resource.knowledge', amount: 34 }],
      unlockCondition: { type: 'upgrade_level_at_least', upgradeId: 'upgrade.learning.observe', level: 1 },
      effects: [{ type: 'producer_multiplier', target: { kind: 'producer', id: 'producer.learning' }, value: 1.35 }],
      graph: { x: 920, y: 360, parentId: 'upgrade.learning.observe' },
    },
    {
      id: 'upgrade.learning.focus',
      name: '专注训练',
      description: '主动点击知识 ×2，并打开下一条知识分支。',
      image: '/assets/derivative.svg',
      category: '学习技能',
      tags: ['learning'],
      cost: [{ resourceId: 'resource.knowledge', amount: 70 }],
      unlockCondition: { type: 'upgrade_level_at_least', upgradeId: 'upgrade.learning.memory', level: 1 },
      effects: [{ type: 'click_multiplier', value: 2 }],
      graph: { x: 1040, y: 500, parentId: 'upgrade.learning.memory' },
    },
    {
      id: 'upgrade.math.number',
      name: '数感',
      description: '所有 mathematics 标签生产者效率 ×1.3。',
      image: '/assets/math.svg',
      category: '数学技能',
      tags: ['mathematics'],
      cost: [{ resourceId: 'resource.math', amount: 15 }],
      unlockCondition: { type: 'producer_level_at_least', producerId: 'producer.math.foundation', level: 2 },
      effects: [{ type: 'producer_multiplier', target: { kind: 'tag', id: 'mathematics' }, value: 1.3 }],
      graph: { x: 1210, y: 370, parentId: 'producer.math.foundation' },
    },
    {
      id: 'upgrade.math.algebra',
      name: '代数直觉',
      description: '数学生产者效率 ×1.5，并继续向微积分推进。',
      image: '/assets/notes.svg',
      category: '数学技能',
      tags: ['mathematics'],
      cost: [{ resourceId: 'resource.math', amount: 45 }],
      unlockCondition: { type: 'upgrade_level_at_least', upgradeId: 'upgrade.math.number', level: 1 },
      effects: [{ type: 'producer_multiplier', target: { kind: 'tag', id: 'mathematics' }, value: 1.5 }],
      graph: { x: 1430, y: 410, parentId: 'upgrade.math.number' },
    },
    {
      id: 'upgrade.math.limit',
      name: '极限',
      description: '微积分生产效率 ×1.5。',
      image: '/assets/limit.svg',
      category: '微积分技能',
      tags: ['mathematics'],
      cost: [{ resourceId: 'resource.math', amount: 120 }],
      unlockCondition: { type: 'producer_level_at_least', producerId: 'producer.math.calculus', level: 2 },
      effects: [{ type: 'producer_multiplier', target: { kind: 'producer', id: 'producer.math.calculus' }, value: 1.5 }],
      graph: { x: 1580, y: 880, parentId: 'producer.math.calculus' },
    },
    {
      id: 'upgrade.math.derivative',
      name: '导数',
      description: '微积分生产效率 ×2。',
      image: '/assets/derivative.svg',
      category: '微积分技能',
      tags: ['mathematics'],
      cost: [{ resourceId: 'resource.math', amount: 260 }],
      unlockCondition: { type: 'upgrade_level_at_least', upgradeId: 'upgrade.math.limit', level: 1 },
      effects: [{ type: 'producer_multiplier', target: { kind: 'producer', id: 'producer.math.calculus' }, value: 2 }],
      graph: { x: 1820, y: 900, parentId: 'upgrade.math.limit' },
    },
  ],
  events: [],
};
